version: '3'

services:
  db:
    image: postgres:alpine
    container_name: postgres_server
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  api:
    build: .
    container_name: node_afiliados
    ports:
      - '3333:3333'
    volumes:
      - ./src:/app
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "echo 'Please wait the migrations ran' && npx prisma generate --schema ./prisma/schema.prisma && yarn build && yarn db:seed && yarn migration:run"
